### ISSUE TITLE
Installation Issue (Please include to your user guide...)

### ISSUE THREAD

**Issue by kiddtang** [zoutapps/laravel-backpack-multiauth#3]
cannot install via `composer require zoutapps/laravel-backpack-multiauth --dev` directly if anyone want to install your package out of the fresh Laravel installation.

Error:
`[InvalidArgumentException]
  Could not find package zoutapps/laravel-backpack-multiauth at any version for your minimum-stability (stable). Check the package spelling or your m
  inimum-stability
`

Can only install by update composer.json

`"require-dev": {
        "zoutapps/laravel-backpack-multiauth": "dev-master",
    },`

**Comment by OliverZiegler** [comment]
As this is more or less an issue with composer and we currently have the "stable-no release" badge in the Readme I think this is not really necessary to change.
If you think this must be mentioned in the readme please create a pull request for the readme.

Closing this issue

**Comment by OliverZiegler** [comment]
As this is more or less an issue with composer and we currently have the "stable-no release" badge in the Readme I think this is not really necessary to change.
If you think this must be mentioned in the readme please create a pull request for the readme.

Closing this.
