### ISSUE TITLE
Can't composer require: Could not find package zoutapps/laravel-backpack-multiauth at any version for your minimum-stability (stable).

### ISSUE THREAD

**Issue by fabiodiniz** [zoutapps/laravel-backpack-multiauth#6]
I'm using Composer 1.4.2, PHP 7.1.1 @ macOS Sierra 10.12.4

When I run "composer require zoutapps/laravel-backpack-multiauth --dev" what I got was:
```
[InvalidArgumentException]
Could not find package zoutapps/laravel-backpack-multiauth at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

Any idea about what's going on? :)

**Comment by OliverZiegler** [comment]
This seems to be more an issue than I thought...
Please refer to #3 

Will update the readme next week...

**Comment by fabiodiniz** [comment]
Thanks for the quickly answer! 😀
