### ISSUE TITLE
views are created on wrong folder "resources" instead of "resources"

### ISSUE THREAD

**Issue by developermedia** [zoutapps/laravel-backpack-multiauth#8]
FYI

Need to updated following file 

zoutapps\laravel-backpack-multiauth\src\Generators\ViewsGenerator.php

line no. 24

Please let me know if I am wrong

**Comment by OliverZiegler** [comment]
It says "recources" which is wrong. So you are right ;)

There was no test at the moment for this. And on the test branch are some more fixes for typos etc. So for the moment try using the test branch ;)

**Comment by OliverZiegler** [comment]
This is now fixed in dev branch.
